config/routes.rb
Micropay::Application.routes.draw do

  resources :microposts
  resources :electronic_purses
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => "pages#home"

end

app/controllers/electronic_purses_controller.rb
class ElectronicPursesController < ApplicationController
  # GET /electronic_purses
  # GET /electronic_purses.xml
  def index
    @electronic_purses = ElectronicPurse.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @electronic_purses }
    end
  end

  # GET /electronic_purses/1
  # GET /electronic_purses/1.xml
  def show
    @electronic_purse = ElectronicPurse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @electronic_purse }
    end
  end

  # GET /electronic_purses/new
  # GET /electronic_purses/new.xml
  def new
    @electronic_purse = ElectronicPurse.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @electronic_purse }
    end
  end

  # GET /electronic_purses/1/edit
  def edit
    @electronic_purse = ElectronicPurse.find(params[:id])
  end

  # POST /electronic_purses
  # POST /electronic_purses.xml
  def create
    @electronic_purse = ElectronicPurse.new(params[:electronic_purse])

    respond_to do |format|
      if @electronic_purse.save
        format.html { redirect_to(@electronic_purse, :notice => 'Electronic purse was successfully created.') }
        format.xml  { render :xml => @electronic_purse, :status => :created, :location => @electronic_purse }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @electronic_purse.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /electronic_purses/1
  # PUT /electronic_purses/1.xml
  def update
    @electronic_purse = ElectronicPurse.find(params[:id])

    respond_to do |format|
      if @electronic_purse.update_attributes(params[:electronic_purse])
        format.html { redirect_to(@electronic_purse, :notice => 'Electronic purse was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @electronic_purse.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /electronic_purses/1
  # DELETE /electronic_purses/1.xml
  def destroy
    @electronic_purse = ElectronicPurse.find(params[:id])
    @electronic_purse.destroy

    respond_to do |format|
      format.html { redirect_to(electronic_purses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/electronic_purses_helper.rb
module ElectronicPursesHelper
end

app/views/electronic_purses/_form.html.erb
<%= form_for(@electronic_purse) do |f| %>
  <% if @electronic_purse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@electronic_purse.errors.count, "error") %> prohibited this electronic_purse from being saved:</h2>

      <ul>
      <% @electronic_purse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :credit %><br />
    <%= f.text_field :credit %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/electronic_purses/edit.html.erb
<h1>Editing electronic_purse</h1>

<%= render 'form' %>

<%= link_to 'Show', @electronic_purse %> |
<%= link_to 'Back', electronic_purses_path %>

app/views/electronic_purses/index.html.erb
<h1>Listing electronic_purses</h1>

<table>
  <tr>
    <th>Credit</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @electronic_purses.each do |electronic_purse| %>
  <tr>
    <td><%= electronic_purse.credit %></td>
    <td><%= electronic_purse.user_id %></td>
    <td><%= link_to 'Show', electronic_purse %></td>
    <td><%= link_to 'Edit', edit_electronic_purse_path(electronic_purse) %></td>
    <td><%= link_to 'Destroy', electronic_purse, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Electronic purse', new_electronic_purse_path %>

app/views/electronic_purses/new.html.erb
<h1>New electronic_purse</h1>

<%= render 'form' %>

<%= link_to 'Back', electronic_purses_path %>

app/views/electronic_purses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Credit:</b>
  <%= @electronic_purse.credit %>
</p>

<p>
  <b>User:</b>
  <%= @electronic_purse.user_id %>
</p>


<%= link_to 'Edit', edit_electronic_purse_path(@electronic_purse) %> |
<%= link_to 'Back', electronic_purses_path %>